# brew tap
tap "caskroom/cask"
tap "buo/cask-upgrade"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "pivotal/tap"
tap "caskroom/fonts"

# brew install
brew "git"
brew "mas"
brew "wget"
brew "yarn"
brew "neovim"
brew "mysql"
brew "node"
brew "n"
brew "zsh"
brew "python3"
